spring:
  application:
    name: Demo
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

## Flyway??
#spring.flyway.enabled=true
#spring.flyway.baseline-on-migrate=true
